name: dev
replicas: 1

image: <+artifact.image>

createNamespace: true
namespace: <+infra.namespace>

serviceType: LoadBalancer

servicePort: 80
serviceTargetPort: 8080
mountpathname: test
key: key1
env:
  config:
    properties: <+secrets.getValue("config")>
