name: dev-deploy
replicas: 1

image: <+artifact.image>

createNamespace: true
namespace: <+infra.namespace>

serviceType: LoadBalancer

servicePort: 80
serviceTargetPort: 8080
mountpathname: dev-deploy
key: key1
env:
  config:
    config.properties: ${configFile.getAsString("config.properties")}
